### ISSUE TITLE
关于coarse_label的小问题

### ISSUE THREAD

**Issue by BotaoPeng98** [Yunfan-Li/Image-Clustering-with-External-Guidance#2]
Yunfan，你好呀！

非常棒的工作！我有一个问题想请教一下你。

在[image_embedding.py](https://github.com/Yunfan-Li/Image-Clustering-with-External-Guidance/blob/main/image_embedding.py)里，这个coarse_label的作用是什么呢？

期待你的回复！

此致，

祝好！

**Comment by Yunfan-Li** [comment]
您好，因为 CIFAR-100 这个数据集有 100 类的细粒度标签和 20 类的粗粒度标签，相关代码是用于细粒度标签向粗粒度标签的转换

**Comment by BotaoPeng98** [comment]
明白了，万分感谢，祝科研工作生活顺利！
